import 'package:paperwings/models/plane_flight_settings.dart';
import 'package:paperwings/models/plane_item.dart';

class PlaneRepository {
  List<PlaneItem> fetchPlanes() {
    return [
      PlaneItem(
        imageUrl: 'assets/planes/black.png',
        title: 'Paper Monster',
        description: "A japanesse inspired plane",
        progress1: 0.3,
        progress2: 0.9,
        progress3: 0.4,
        defaultSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
        customSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
      ),
      PlaneItem(
        imageUrl: 'assets/planes/blue.png',
        title: 'K22 Destroyer',
        description: "Plane to win a war",
        progress1: 0.1,
        progress2: 0.7,
        progress3: 0.2,
        defaultSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
        customSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
      ),
      PlaneItem(
        imageUrl: 'assets/planes/orange.png',
        title: 'H22',
        description: "A japanesse inspired plane",
        progress1: 0.1,
        progress2: 0.4,
        progress3: 0.9,
        defaultSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
        customSettings: PlaneFlightSettings(
          steeringAngle: 110,
          pitchKp: 1.5,
          pitchKi: 0.1,
          pitchKd: 0.05,
          rollKp: 0.3,
          rollKi: 0.05,
          rollKd: 0.02,
          yawKp: 0.5,
          yawKi: 0.05,
          yawKd: 0.02,
          angleOfAttack: 5,
          beacon: 0,
        ),
      ),
    ];
  }
}
